title: aritagrade
description: "Portfolio of product designer Rita Grade"

baseurl: "/myportfolio2"
url: ""

github_username:  ritagrade
email: aritagrade@gmail.com
tel: +351 910 000 000
address: Lisbon, Portugal
timezone: Europe/Lisbon
year: 2021
sitemap: true

social-username:
  linkedin: "argdesinger"
  github: "ritagrade"
  behance: "argdesinger"
  dribbble: "argdesinger"

permalink: /:title/

image_serve_path: "/assets/images" # <img src="{{ site.image_serve_path }}/projects/img.jpg">

collections:
  projects:
    output: true
    permalink: /projects/:path/
  fonts:
    output: true
    permalink: /fonts/:path/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "fonts"
    values:
      layout: "font"

sass:
    sass_dir: _sass
    style: :compressed

lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge