title: aritagrade
description: "Portfolio of product designer Rita Grade"

baseurl: "/myportfolio2"
url: ""

github_username:  ritagrade
email: aritagrade@gmail.com
tel: +351 910 000 000
address: Lisbon, Portugal
timezone: Europe/Lisbon
year: 2021
sitemap: true

social-username:
  linkedin: "argdesinger"
  github: "ritagrade"
  behance: "argdesinger"
  dribbble: "argdesinger"

permalink: /:title/

image_serve_path: "/assets/images"

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

sass:
    sass_dir: _sass
    style: :compressed

